# theme: jekyll-theme-midnight
remote_theme: broccolini/swiss
theme_color: gray

title: aurum portfolio
description: a portfolio for aurumcodex

github_repo: aurumcodex.github.io
github_username: aurumcodex

social_link: twitter
social_username: aurum_codex